### ISSUE TITLE
update docs, templates and wtd variables

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-yum-cron#2]
below things are not on the latest state
- docs
- LICENSE.md
- variable naming
- meta files

**Comment by Cinux90** [comment]
Create branch update_meta for update actions.
https://github.com/while-true-do/ansible-role-yum-cron/tree/update_meta
Add prefix to variablen name and adjust Licence and Meta file.
@daniel-wtd maybe you can look into it and check if its fit :) Thanks!

**Comment by dschier-wtd** [comment]
looks fine from my side. Please open up a PR.

**Comment by daniel-wtd** [comment]
argl, it does not. the templates are still using the old vars.

**Comment by dschier-wtd** [comment]
...me, found another issue with this ^^ will open it.
